<%
  local_env = {}
  if Rails.env.development? || Rails.env.test?
    branch = %x[git rev-parse --abbrev-ref HEAD].strip rescue nil
    branch = branch.gsub('/', '_')
    branch = branch.gsub('.', '_')
    local_env = YAML.load_file("#{Rails.root}/local_env.yml").dig(Rails.env) || {}

    changes_count = %x[git ls-files -mo --exclude-standard -- #{Rails.root}/db | wc -l].strip rescue nil
    diffs_count = %x[git diff --cached master --name-only -- #{Rails.root}/db | wc -l].strip rescue nil

    if 0 >= changes_count.to_i + diffs_count.to_i
      branch = 'master'
    end

    if(local_env.dig('devdb') != nil)
      branch = local_env.dig('devdb')
    end
  end
%>

development:
  encoding: utf8mb4
  collation: utf8mb4_bin
  adapter:   mysql2
  database:  catan_development_<%= branch %>
  username:  <%= local_env.dig('database', 'username') %>
  password:  <%= local_env.dig('database', 'password') %>

default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

test:
  encoding: utf8mb4
  collation: utf8mb4_bin
  adapter:   mysql2
  database:  catan_test_<%= branch %>
  username:  <%= local_env.dig('database', 'username') %>
  password:  <%= local_env.dig('database', 'password') %>

production:
  adapter:    mysql2
  database:   '<%= ENV.fetch("DATABASE_NAME") { "DEFAULT_DATABASE_NAME" } %>'
  username:   '<%= ENV.fetch("DATABASE_USERNAME") { "DEFAULT_DATABASE_USERNAME" } %>'
  password:   '<%= ENV.fetch("DATABASE_PASSWORD") { "DEFAULT_DATABASE_PASSWORD" } %>'
  host:       '<%= ENV.fetch("DATABASE_HOST") { "DEFAULT_DATABASE_HOST" } %>'
  pool:       <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding:   utf8mb4
  collation:  utf8mb4_unicode_ci
  reconnect:  true

