score_job:
  cron: "1 * * * * Asia/Seoul"
  class: "ScoreJob"
  queue: default
analyze_job:
  cron: "0 1 * * * Asia/Seoul"
  class: "AnalyzeJob"
  queue: default
survey_closed_message_job:
  cron: "*/40 * * * * Asia/Seoul"
  class: "SurveyClosedMessagesJob"
  queue: default
summary_job:
  cron: "*/25 * * * 1 Asia/Seoul"
  class: "SummaryJob"
  queue: default
active_issue_stats_job:
  cron: "0 2 * * * Asia/Seoul"
  class: "MonitorActiveIssuesJob"
  queue: default
zombie_group_member_purge_job:
  cron: "30 * * * * Asia/Seoul"
  class: "ZombieGroupMemberPurgeJob"
  queue: default
monitor_posts_error_job:
  cron: "5 * * * * Asia/Seoul"
  class: "MonitorPostsErrorJob"
  queue: default
last_stroked_posts_count_job:
  cron: "*/45 * * * * Asia/Seoul"
  class: "LastStrokedPostsCountJob"
  queue: default
