score_job:
  cron: "1 * * * * Asia/Seoul"
  class: "ScoreJob"
  queue: default
analyze_job:
  cron: "0 1 * * * Asia/Seoul"
  class: "AnalyzeJob"
  queue: default
survey_closed_message_job:
  cron: "*/40 * * * * Asia/Seoul"
  class: "SurveyClosedMessagesJob"
  queue: default
summary_job:
  cron: "*/25 * * * 1 Asia/Seoul"
  class: "SummaryJob"
  queue: default
