# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f98bc41312efa639af653574eb49d6cd25f397f60d8f1fa55a5a8dc1913920e8f14265ad8fdf9ab7df406ae6790eab3ea85ddb7531aa726f50085e86950966f

test:
  secret_key_base: 7f86b1c8769c7251945d25f2537abd03660cec4e652b9d66d0e1cee7feb57e50a54a3ab2176c087befdac8813e5d5a9603f2fa0c690ce04ccd494324f0d9b8df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
